### PR TITLE
add Simplified Chinese tranlation

### PR DESCRIPTION
**Pull request by Lzw104522773**
add Simplified Chinese tranlation

### CODE REVIEW

**Comment by burner1024** [comment]
Don't need anything in tra_ee directory.

**Comment by Lzw104522773** [comment]
If there is no tra file in the tra_ee folder, the installation will fail, and the tp2 file needs to be found in the tra_ee folder for the setup file. I don't know how to handle it. *@ο@*

**Comment by Lzw104522773** [comment]
If there is no tra file in the tra_ee folder, the installation will fail, and the tp2 file needs to be found in the tra_ee folder for the setup file. I don't know how to handle it. @ο@

**Comment by burner1024** [comment]
Don't worry about that, it's handled by [handle-charsets](https://github.com/BGforgeNet/handle-charsets).

**Comment by Lzw104522773** [comment]
I deleted the  schinese subfolder from tra_ee folder,and intall this mod,weidu display the information at blow:

[D:\Baldur's Gate II Enhanced Edition\setup-wildmage.exe] WeiDU version 24900

Choose your language:
 0 [English]
 1 [Deutsch]
 2 [Francais (d'Oghmatiques)]
 3 [Polski (Maciek F)]
 4 [Brazilian Portuguese]
 5 [Russian (aerie.ru)]
 6 [Swedish]
 7 [Simplified Chinese]
7
Using Language [Simplified Chinese]

Please choose the language in which you wish to play the game.
If you later wish to play the game in a different language you will need to edit the file weidu.conf and reinstall your mods.
 0 [German]
 1 [English]
 2 [Spanish]
 3 [French]
 4 [Italian]
 5 [Korean]
 6 [Polish]
 7 [Russian]
 8 [Simplified Chinese]
8

Using .\lang\zh_cn\dialog.tlk
ERROR: No translation provided for @60
Continuing despite error.
ERROR: No translation provided for @1
Continuing despite error.
ERROR: No translation provided for @1
Continuing despite error.

Install Component [UNDEFINED STRING:   @1]?
[N]o, [Q]uit or choose one:
ERROR: No translation provided for @60
Continuing despite error.
 1] UNDEFINED STRING:   @60

**Comment by Lzw104522773** [comment]
I see

**Pull request closed without merging**
