### PR TITLE
add Simplified Chinese tranlation

### PR DESCRIPTION
**Pull request by Lzw104522773**
add Simplified Chinese tranlation.
I deleted the mod‘s fork and then re-fork, so there should be no problem now.
I apologize for my operational error.

### CODE REVIEW

**Comment by burner1024** [comment]
You can just keep pushing to the same branch, I'll squash it anyway.

**Comment by Lzw104522773** [comment]
Sorry,I want to know when can you merge pull requests from me?I want to make a NEW EET with this mod.
.

**Comment by Lzw104522773** [comment]
update setup.tra translatio

**Comment by burner1024** [comment]
> Sorry,I want to know when can you merge pull requests from me?I want to make a NEW EET with this mod.

When it's looking good. Right now it doesn't, see the above comment.

**Pull request closed without merging**
